/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthLoginSchema,
  AuthResponse,
  HTTPValidationError,
  UserCreateSchema
} from '.././model';





/**
 * @summary Register
 */
export const registerAuthRegisterPost = (
    userCreateSchema: UserCreateSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/auth/register`,
      userCreateSchema,options
    );
  }



export const getRegisterAuthRegisterPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerAuthRegisterPost>>, TError,{data: UserCreateSchema}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof registerAuthRegisterPost>>, TError,{data: UserCreateSchema}, TContext> => {

const mutationKey = ['registerAuthRegisterPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerAuthRegisterPost>>, {data: UserCreateSchema}> = (props) => {
          const {data} = props ?? {};

          return  registerAuthRegisterPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerAuthRegisterPost>>>
    export type RegisterAuthRegisterPostMutationBody = UserCreateSchema
    export type RegisterAuthRegisterPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Register
 */
export const useRegisterAuthRegisterPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerAuthRegisterPost>>, TError,{data: UserCreateSchema}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerAuthRegisterPost>>,
        TError,
        {data: UserCreateSchema},
        TContext
      > => {

      const mutationOptions = getRegisterAuthRegisterPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Login
 */
export const loginAuthLoginPost = (
    authLoginSchema: AuthLoginSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/auth/login`,
      authLoginSchema,options
    );
  }



export const getLoginAuthLoginPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: AuthLoginSchema}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: AuthLoginSchema}, TContext> => {

const mutationKey = ['loginAuthLoginPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAuthLoginPost>>, {data: AuthLoginSchema}> = (props) => {
          const {data} = props ?? {};

          return  loginAuthLoginPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginPost>>>
    export type LoginAuthLoginPostMutationBody = AuthLoginSchema
    export type LoginAuthLoginPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: AuthLoginSchema}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAuthLoginPost>>,
        TError,
        {data: AuthLoginSchema},
        TContext
      > => {

      const mutationOptions = getLoginAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Me
 */
export const meAuthMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    
    
    return axios.get(
      `http://127.0.0.1:8000/auth/me`,options
    );
  }




export const getMeAuthMeGetQueryKey = () => {
    return [
    `http://127.0.0.1:8000/auth/me`
    ] as const;
    }

    
export const getMeAuthMeGetQueryOptions = <TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeAuthMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof meAuthMeGet>>> = ({ signal }) => meAuthMeGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof meAuthMeGet>>>
export type MeAuthMeGetQueryError = AxiosError<unknown>


export function useMeAuthMeGet<TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof meAuthMeGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeAuthMeGet<TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof meAuthMeGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeAuthMeGet<TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useMeAuthMeGet<TData = Awaited<ReturnType<typeof meAuthMeGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meAuthMeGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Patch Me
 */
export const patchMeAuthMePatch = (
    userCreateSchema: UserCreateSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    
    
    return axios.patch(
      `http://127.0.0.1:8000/auth/me`,
      userCreateSchema,options
    );
  }



export const getPatchMeAuthMePatchMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeAuthMePatch>>, TError,{data: UserCreateSchema}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof patchMeAuthMePatch>>, TError,{data: UserCreateSchema}, TContext> => {

const mutationKey = ['patchMeAuthMePatch'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMeAuthMePatch>>, {data: UserCreateSchema}> = (props) => {
          const {data} = props ?? {};

          return  patchMeAuthMePatch(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchMeAuthMePatchMutationResult = NonNullable<Awaited<ReturnType<typeof patchMeAuthMePatch>>>
    export type PatchMeAuthMePatchMutationBody = UserCreateSchema
    export type PatchMeAuthMePatchMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Patch Me
 */
export const usePatchMeAuthMePatch = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeAuthMePatch>>, TError,{data: UserCreateSchema}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchMeAuthMePatch>>,
        TError,
        {data: UserCreateSchema},
        TContext
      > => {

      const mutationOptions = getPatchMeAuthMePatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    