/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponseSchema } from './userResponseSchema';

export interface AuthResponse {
  user: UserResponseSchema;
  access_token: string;
}
