/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorResponsePinId } from './sensorResponsePinId';

export interface SensorResponse {
  id: number;
  label: string;
  pin_id: SensorResponsePinId;
  range_min: number;
  range_max: number;
  type: string;
  in_out: boolean;
}
