/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserResponseSchema {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** @maxLength 128 */
  email: string;
  /** @maxLength 128 */
  password: string;
  /** @maxLength 9 */
  phone_number: string;
  readonly created_at: string;
  readonly updated_at: string;
}
