/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserCreateSchema {
  email: string;
  password: string;
  phone_number: string;
}
