/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AppModelsSensorModelSensor2lqljyLeafPinIdAnyOf } from './appModelsSensorModelSensor2lqljyLeafPinIdAnyOf';

export type AppModelsSensorModelSensor2lqljyLeafPinId = AppModelsSensorModelSensor2lqljyLeafPinIdAnyOf | unknown[];
