/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AppModelsSensorModelSensor2lqljyLeafLabel } from './appModelsSensorModelSensor2lqljyLeafLabel';
import type { AppModelsSensorModelSensor2lqljyLeafPinId } from './appModelsSensorModelSensor2lqljyLeafPinId';
import type { SensorType } from './sensorType';

export interface AppModelsSensorModelSensor2lqljyLeaf {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** @nullable */
  label?: AppModelsSensorModelSensor2lqljyLeafLabel;
  pin_id: AppModelsSensorModelSensor2lqljyLeafPinId;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_min: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_max: number;
  /**
   * OTHER: other
   * @maxLength 32
   */
  type: SensorType;
  in_out: boolean;
}
