/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionType } from './conditionType';
import type { ActionUpdateSchema } from './actionUpdateSchema';
import type { ActionCreateSchema } from './actionCreateSchema';

export interface AutomationUpdateSchema {
  /** @maxLength 255 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  on_value: number;
  /**
   * LT: lt<br/>GT: gt<br/>EQ: eq
   * @maxLength 2
   */
  condition: ConditionType;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  sensor_id: number;
  actions: ActionUpdateSchema[];
  new_actions: ActionCreateSchema[];
  delete_actions?: number[];
}
