/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ConditionType = typeof ConditionType[keyof typeof ConditionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConditionType = {
  lt: 'lt',
  gt: 'gt',
  eq: 'eq',
} as const;
