/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceResponseLabel } from './deviceResponseLabel';
import type { DeviceResponseUserId } from './deviceResponseUserId';
import type { SensorResponse } from './sensorResponse';

export interface DeviceResponse {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** @nullable */
  label?: DeviceResponseLabel;
  /** @maxLength 12 */
  mac_address: string;
  /** @nullable */
  user_id?: DeviceResponseUserId;
  sensors: SensorResponse[];
}
