/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceAttachLabel } from './deviceAttachLabel';

export interface DeviceAttach {
  /** @nullable */
  label?: DeviceAttachLabel;
}
