/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DevicesDevicesGetParams = {
page?: number | null;
per_page?: number | null;
offset?: number | null;
search?: string | null;
};
