/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorCreate } from './sensorCreate';

export interface DeviceCreate {
  /** @maxLength 12 */
  mac_address: string;
  sensors: SensorCreate[];
}
