/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorResponseLabel } from './sensorResponseLabel';
import type { SensorResponsePinId } from './sensorResponsePinId';
import type { SensorType } from './sensorType';
import type { SensorResponseDeviceId } from './sensorResponseDeviceId';

export interface SensorResponse {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** @nullable */
  label?: SensorResponseLabel;
  pin_id: SensorResponsePinId;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_min: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_max: number;
  /**
   * OTHER: other
   * @maxLength 32
   */
  type: SensorType;
  in_out: boolean;
  /** @nullable */
  device_id?: SensorResponseDeviceId;
}
