/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorCreateLabel } from './sensorCreateLabel';
import type { SensorCreatePinId } from './sensorCreatePinId';
import type { SensorType } from './sensorType';
import type { SensorCreateDeviceId } from './sensorCreateDeviceId';

export interface SensorCreate {
  /** @nullable */
  label?: SensorCreateLabel;
  pin_id: SensorCreatePinId;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_min: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_max: number;
  /**
   * OTHER: other
   * @maxLength 32
   */
  type: SensorType;
  in_out: boolean;
  /** @nullable */
  device_id?: SensorCreateDeviceId;
}
