/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorWithValuesResponsePinIdAnyOf } from './sensorWithValuesResponsePinIdAnyOf';

export type SensorWithValuesResponsePinId = SensorWithValuesResponsePinIdAnyOf | unknown[];
