/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorWithValuesResponseLabel } from './sensorWithValuesResponseLabel';
import type { SensorWithValuesResponsePinId } from './sensorWithValuesResponsePinId';
import type { SensorType } from './sensorType';
import type { SensorWithValuesResponseDeviceId } from './sensorWithValuesResponseDeviceId';
import type { SensorValueResponse } from './sensorValueResponse';

export interface SensorWithValuesResponse {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** @nullable */
  label?: SensorWithValuesResponseLabel;
  pin_id: SensorWithValuesResponsePinId;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_min: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  range_max: number;
  /**
   * OTHER: other
   * @maxLength 32
   */
  type: SensorType;
  in_out: boolean;
  /** @nullable */
  device_id?: SensorWithValuesResponseDeviceId;
  sensor_values: SensorValueResponse[];
}
