/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SensorType = typeof SensorType[keyof typeof SensorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorType = {
  other: 'other',
} as const;
