/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SensorCreatePinIdAnyOf } from './sensorCreatePinIdAnyOf';

export type SensorCreatePinId = SensorCreatePinIdAnyOf | unknown[];
