/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SensorValueResponse {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  value: number;
  readonly timestamp: string;
}
