/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AutomationCreateSchema,
  AutomationResponseSchema,
  AutomationsAutomationGetParams,
  HTTPValidationError
} from '.././model';





/**
 * @summary Automations
 */
export const automationsAutomationGet = (
    params?: AutomationsAutomationGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AutomationResponseSchema>> => {
    
    
    return axios.get(
      `http://127.0.0.1:8000/automation/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getAutomationsAutomationGetQueryKey = (params?: AutomationsAutomationGetParams,) => {
    return [
    `http://127.0.0.1:8000/automation/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAutomationsAutomationGetQueryOptions = <TData = Awaited<ReturnType<typeof automationsAutomationGet>>, TError = AxiosError<HTTPValidationError>>(params?: AutomationsAutomationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof automationsAutomationGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAutomationsAutomationGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof automationsAutomationGet>>> = ({ signal }) => automationsAutomationGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof automationsAutomationGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AutomationsAutomationGetQueryResult = NonNullable<Awaited<ReturnType<typeof automationsAutomationGet>>>
export type AutomationsAutomationGetQueryError = AxiosError<HTTPValidationError>


export function useAutomationsAutomationGet<TData = Awaited<ReturnType<typeof automationsAutomationGet>>, TError = AxiosError<HTTPValidationError>>(
 params: undefined |  AutomationsAutomationGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof automationsAutomationGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof automationsAutomationGet>>,
          TError,
          Awaited<ReturnType<typeof automationsAutomationGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutomationsAutomationGet<TData = Awaited<ReturnType<typeof automationsAutomationGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: AutomationsAutomationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof automationsAutomationGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof automationsAutomationGet>>,
          TError,
          Awaited<ReturnType<typeof automationsAutomationGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutomationsAutomationGet<TData = Awaited<ReturnType<typeof automationsAutomationGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: AutomationsAutomationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof automationsAutomationGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Automations
 */

export function useAutomationsAutomationGet<TData = Awaited<ReturnType<typeof automationsAutomationGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: AutomationsAutomationGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof automationsAutomationGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAutomationsAutomationGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create
 */
export const createAutomationPost = (
    automationCreateSchema: AutomationCreateSchema, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AutomationResponseSchema>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/automation/`,
      automationCreateSchema,options
    );
  }



export const getCreateAutomationPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAutomationPost>>, TError,{data: AutomationCreateSchema}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createAutomationPost>>, TError,{data: AutomationCreateSchema}, TContext> => {

const mutationKey = ['createAutomationPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAutomationPost>>, {data: AutomationCreateSchema}> = (props) => {
          const {data} = props ?? {};

          return  createAutomationPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAutomationPostMutationResult = NonNullable<Awaited<ReturnType<typeof createAutomationPost>>>
    export type CreateAutomationPostMutationBody = AutomationCreateSchema
    export type CreateAutomationPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create
 */
export const useCreateAutomationPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAutomationPost>>, TError,{data: AutomationCreateSchema}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAutomationPost>>,
        TError,
        {data: AutomationCreateSchema},
        TContext
      > => {

      const mutationOptions = getCreateAutomationPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    