/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeviceAttach,
  DeviceCreate,
  DeviceResponse,
  DeviceUpdate,
  DevicesDevicesGetParams,
  HTTPValidationError,
  SensorResponse
} from '.././model';





/**
 * @summary Devices
 */
export const devicesDevicesGet = (
    params?: DevicesDevicesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeviceResponse[]>> => {
    
    
    return axios.get(
      `http://127.0.0.1:8000/devices/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDevicesDevicesGetQueryKey = (params?: DevicesDevicesGetParams,) => {
    return [
    `http://127.0.0.1:8000/devices/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDevicesDevicesGetQueryOptions = <TData = Awaited<ReturnType<typeof devicesDevicesGet>>, TError = AxiosError<HTTPValidationError>>(params?: DevicesDevicesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof devicesDevicesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDevicesDevicesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof devicesDevicesGet>>> = ({ signal }) => devicesDevicesGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof devicesDevicesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DevicesDevicesGetQueryResult = NonNullable<Awaited<ReturnType<typeof devicesDevicesGet>>>
export type DevicesDevicesGetQueryError = AxiosError<HTTPValidationError>


export function useDevicesDevicesGet<TData = Awaited<ReturnType<typeof devicesDevicesGet>>, TError = AxiosError<HTTPValidationError>>(
 params: undefined |  DevicesDevicesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof devicesDevicesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof devicesDevicesGet>>,
          TError,
          Awaited<ReturnType<typeof devicesDevicesGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDevicesDevicesGet<TData = Awaited<ReturnType<typeof devicesDevicesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: DevicesDevicesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof devicesDevicesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof devicesDevicesGet>>,
          TError,
          Awaited<ReturnType<typeof devicesDevicesGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDevicesDevicesGet<TData = Awaited<ReturnType<typeof devicesDevicesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: DevicesDevicesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof devicesDevicesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Devices
 */

export function useDevicesDevicesGet<TData = Awaited<ReturnType<typeof devicesDevicesGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: DevicesDevicesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof devicesDevicesGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDevicesDevicesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create
 */
export const createDevicesPost = (
    deviceCreate: DeviceCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeviceResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/devices/`,
      deviceCreate,options
    );
  }



export const getCreateDevicesPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDevicesPost>>, TError,{data: DeviceCreate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createDevicesPost>>, TError,{data: DeviceCreate}, TContext> => {

const mutationKey = ['createDevicesPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDevicesPost>>, {data: DeviceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createDevicesPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDevicesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDevicesPost>>>
    export type CreateDevicesPostMutationBody = DeviceCreate
    export type CreateDevicesPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create
 */
export const useCreateDevicesPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDevicesPost>>, TError,{data: DeviceCreate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDevicesPost>>,
        TError,
        {data: DeviceCreate},
        TContext
      > => {

      const mutationOptions = getCreateDevicesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Device
 */
export const deviceDevicesIdGet = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeviceResponse>> => {
    
    
    return axios.get(
      `http://127.0.0.1:8000/devices/${id}`,options
    );
  }




export const getDeviceDevicesIdGetQueryKey = (id?: number,) => {
    return [
    `http://127.0.0.1:8000/devices/${id}`
    ] as const;
    }

    
export const getDeviceDevicesIdGetQueryOptions = <TData = Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError = AxiosError<HTTPValidationError>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeviceDevicesIdGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deviceDevicesIdGet>>> = ({ signal }) => deviceDevicesIdGet(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeviceDevicesIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof deviceDevicesIdGet>>>
export type DeviceDevicesIdGetQueryError = AxiosError<HTTPValidationError>


export function useDeviceDevicesIdGet<TData = Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deviceDevicesIdGet>>,
          TError,
          Awaited<ReturnType<typeof deviceDevicesIdGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeviceDevicesIdGet<TData = Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deviceDevicesIdGet>>,
          TError,
          Awaited<ReturnType<typeof deviceDevicesIdGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeviceDevicesIdGet<TData = Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Device
 */

export function useDeviceDevicesIdGet<TData = Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deviceDevicesIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeviceDevicesIdGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update
 */
export const updateDevicesIdPatch = (
    id: number,
    deviceUpdate: DeviceUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeviceResponse>> => {
    
    
    return axios.patch(
      `http://127.0.0.1:8000/devices/${id}`,
      deviceUpdate,options
    );
  }



export const getUpdateDevicesIdPatchMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDevicesIdPatch>>, TError,{id: number;data: DeviceUpdate}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateDevicesIdPatch>>, TError,{id: number;data: DeviceUpdate}, TContext> => {

const mutationKey = ['updateDevicesIdPatch'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDevicesIdPatch>>, {id: number;data: DeviceUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDevicesIdPatch(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDevicesIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateDevicesIdPatch>>>
    export type UpdateDevicesIdPatchMutationBody = DeviceUpdate
    export type UpdateDevicesIdPatchMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update
 */
export const useUpdateDevicesIdPatch = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDevicesIdPatch>>, TError,{id: number;data: DeviceUpdate}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDevicesIdPatch>>,
        TError,
        {id: number;data: DeviceUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateDevicesIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete
 */
export const deleteDevicesIdDelete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeviceResponse>> => {
    
    
    return axios.delete(
      `http://127.0.0.1:8000/devices/${id}`,options
    );
  }



export const getDeleteDevicesIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesIdDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesIdDelete>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteDevicesIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDevicesIdDelete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteDevicesIdDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDevicesIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDevicesIdDelete>>>
    
    export type DeleteDevicesIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete
 */
export const useDeleteDevicesIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesIdDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDevicesIdDelete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteDevicesIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Attach
 */
export const attachDevicesMacAddressPut = (
    macAddress: string,
    deviceAttach: DeviceAttach, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeviceResponse>> => {
    
    
    return axios.put(
      `http://127.0.0.1:8000/devices/${macAddress}`,
      deviceAttach,options
    );
  }



export const getAttachDevicesMacAddressPutMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attachDevicesMacAddressPut>>, TError,{macAddress: string;data: DeviceAttach}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof attachDevicesMacAddressPut>>, TError,{macAddress: string;data: DeviceAttach}, TContext> => {

const mutationKey = ['attachDevicesMacAddressPut'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof attachDevicesMacAddressPut>>, {macAddress: string;data: DeviceAttach}> = (props) => {
          const {macAddress,data} = props ?? {};

          return  attachDevicesMacAddressPut(macAddress,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AttachDevicesMacAddressPutMutationResult = NonNullable<Awaited<ReturnType<typeof attachDevicesMacAddressPut>>>
    export type AttachDevicesMacAddressPutMutationBody = DeviceAttach
    export type AttachDevicesMacAddressPutMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Attach
 */
export const useAttachDevicesMacAddressPut = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof attachDevicesMacAddressPut>>, TError,{macAddress: string;data: DeviceAttach}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof attachDevicesMacAddressPut>>,
        TError,
        {macAddress: string;data: DeviceAttach},
        TContext
      > => {

      const mutationOptions = getAttachDevicesMacAddressPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Sensor
 */
export const sensorDevicesIdSensorsSensorIdGet = (
    id: number,
    sensorId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SensorResponse[]>> => {
    
    
    return axios.get(
      `http://127.0.0.1:8000/devices/${id}/sensors/${sensorId}`,options
    );
  }




export const getSensorDevicesIdSensorsSensorIdGetQueryKey = (id?: number,
    sensorId?: number,) => {
    return [
    `http://127.0.0.1:8000/devices/${id}/sensors/${sensorId}`
    ] as const;
    }

    
export const getSensorDevicesIdSensorsSensorIdGetQueryOptions = <TData = Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError = AxiosError<HTTPValidationError>>(id: number,
    sensorId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSensorDevicesIdSensorsSensorIdGetQueryKey(id,sensorId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>> = ({ signal }) => sensorDevicesIdSensorsSensorIdGet(id,sensorId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id && sensorId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SensorDevicesIdSensorsSensorIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>>
export type SensorDevicesIdSensorsSensorIdGetQueryError = AxiosError<HTTPValidationError>


export function useSensorDevicesIdSensorsSensorIdGet<TData = Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number,
    sensorId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>,
          TError,
          Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSensorDevicesIdSensorsSensorIdGet<TData = Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number,
    sensorId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>,
          TError,
          Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSensorDevicesIdSensorsSensorIdGet<TData = Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number,
    sensorId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sensor
 */

export function useSensorDevicesIdSensorsSensorIdGet<TData = Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError = AxiosError<HTTPValidationError>>(
 id: number,
    sensorId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sensorDevicesIdSensorsSensorIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSensorDevicesIdSensorsSensorIdGetQueryOptions(id,sensorId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



